SERVICE_PORT = 8080

SERVICE_USE_TCP_ENV_VAR = 'RPYC_USE_TCP'

MAIN_LOGGER_NAME = 'RPyC-Main'
SERVER_LOGGER_NAME = 'Server'

ANY_CID = -1
CID_STRUCT_FORMAT = '<L'
UNIX_VSOCK_DEVICE_PATH = '/dev/vsock'
